[package]
name = "tauri-plugin-main-js"
version = "0.0.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.57"
exclude = ["/examples"]

[dependencies]
deno_core = "0.151.0"
tauri = { version = "1.1.1" }

[workspace]
members = [
  "examples/*/src-tauri",
]